import { describe, expect, it } from "vitest";
import { feasibilityScreen } from "./feasibility";
import { buildMacrocycle } from "./macrocycle";
import { DEFAULT_SAFETY_FLAGS } from "./intake";
import type { AthleteState, Goal } from "./intake";

/*
 * A projection may not promise what the block does not prescribe.
 *
 * `feasibilityScreen` derived the endurance gain from training age, block
 * length and the priority split. Volume was not one of its inputs, so it
 * returned the same forecast whether the plan contained two runs a week or
 * six — and that forecast is printed to the athlete as "reachable" or
 * "ambitious" alongside a target time.
 *
 * The athlete who reported this: 18:25 for 5k, working toward 18:00, given one
 * run a week. The plan said the target was reachable. Both halves of that were
 * generated by the same engine from the same inputs, and they contradicted
 * each other.
 */

const state = (currentRunMinPerWeek: number): AthleteState =>
  ({
    bodyweightKg: 75,
    heightCm: 180,
    age: 28,
    sex: "male",
    oneRms: { squat: 140, bench: 100, deadlift: 180 },
    predicted5kS: 1105, // 18:25
    predicted5kFromEffort: true,
    strengthTrainingAge: "intermediate",
    enduranceTrainingAge: "advanced",
    strengthTrainingYears: 4,
    enduranceTrainingYears: 8,
    currentRunMinPerWeek,
    currentStrengthSessionsPerWeek: 2,
    chronicLoad: 300,
    restingHr: 48,
    maxHr: 192,
    safety: { ...DEFAULT_SAFETY_FLAGS, injuryLast12Weeks: false, surgeryLast6Months: false },
    assumed: [],
  }) as AthleteState;

const goal = (): Goal =>
  ({
    weeksOut: 12,
    horizonSource: "event_date",
    target5kS: 1080, // 18:00
    enduranceEventKm: 5,
    enduranceEventKey: "5k",
    targetSquatKg: 160,
    targetBenchKg: 110,
    targetDeadliftKg: 200,
    targetTotalKg: 470,
    priority: 0.35,
    sameDay: false,
    interEventGapH: 0,
    weightClassKg: null,
    eventOrderKnown: false,
  }) as Goal;

describe("the projection is bounded by the volume the plan prescribes", () => {
  it("projects a faster 5k off a block that actually contains running", () => {
    const ample = feasibilityScreen(state(200), goal());
    expect(ample.projected5kS).toBeLessThan(1105);
  });

  it("projects less improvement off a thin block than off an ample one", () => {
    /*
     * The heart of it. Same athlete, same target, same twelve weeks, same
     * training age — the ONLY difference is how much running the block
     * contains. Before volume reached this function these two were identical.
     */
    const thin = feasibilityScreen(state(25), goal());
    const ample = feasibilityScreen(state(200), goal());
    expect(thin.projected5kS).toBeGreaterThan(ample.projected5kS);
  });

  it("never claims a thin block reaches a target an ample one only just reaches", () => {
    const thin = feasibilityScreen(state(25), goal());
    const ample = feasibilityScreen(state(200), goal());
    // Whatever the ample block is judged to do, the thin one cannot be judged
    // to do more of it.
    if (!ample.enduranceReachable) expect(thin.enduranceReachable).toBe(false);
  });

  it("does not inflate a projection when the block exceeds what the target needs", () => {
    // volumeSupport is capped at 1. A 400 min/week block does not get a bonus
    // over the volume an 18:00 is built on — more running than the target
    // requires is not a licence to project beyond the athlete's own rate.
    const ample = feasibilityScreen(state(200), goal());
    const enormous = feasibilityScreen(state(400), goal());
    expect(enormous.projected5kS).toBeGreaterThanOrEqual(ample.projected5kS - 1e-9);
  });

  it("leaves an athlete with no 5k target unaffected", () => {
    const noTarget = { ...goal(), target5kS: null } as Goal;
    const thin = feasibilityScreen(state(25), noTarget);
    // Nothing to measure volume against, so the projection is untouched.
    expect(thin.projected5kS).toBeLessThan(1105);
  });
});

describe("it says when volume is the thing holding the projection back", () => {
  const volumeNote = (msgs: string[]) =>
    msgs.find((m) => m.includes("limited by how much running this block contains"));

  it("tells a thin block that the limit is volume, and where to change it", () => {
    const thin = feasibilityScreen(state(25), goal());
    const note = volumeNote(thin.messages);
    expect(note, "no volume note on a block that cannot reach the target").toBeTruthy();
    // It has to name the fix, not just the diagnosis. "Ambitious" alone reads
    // as a verdict on the athlete rather than on a number they can correct.
    expect(note).toMatch(/intake/i);
    expect(note).toMatch(/not recorded/i);
    // And quote both figures, so the gap is legible rather than asserted.
    expect(note).toMatch(/min\/week/);
  });

  it("does not raise it when the block already carries the volume", () => {
    // For this athlete the shortfall would be real, and blaming volume would
    // send them to change a number that is already right.
    const ample = feasibilityScreen(state(400), goal());
    expect(volumeNote(ample.messages)).toBeUndefined();
  });
});

describe("the figure it quotes is the figure the plan prescribes", () => {
  it("quotes the block's real peak, not the ramp's ceiling", () => {
    /*
     * The first version multiplied the on-ramp anchor by ONRAMP_MAX_MULTIPLE.
     * That is the cap the ramp may not pass, not the volume it reaches — over
     * twelve weeks with deloads it gets nowhere near 2.6x. The message told the
     * reported athlete their block built to 163 min/week when the plan
     * prescribed 73, which is the whole defect class this engine's own
     * comments keep warning about: quoting a number the plan then contradicts.
     */
    const s = state(25);
    const g = goal();
    const quoted = feasibilityScreen(s, g).messages
      .find((m) => m.includes("It builds to about"))
      ?.match(/It builds to about (\d+) min\/week/)?.[1];
    expect(quoted, "no peak quoted").toBeTruthy();

    const realPeak = Math.max(...buildMacrocycle(s, g).map((w) => w.enduranceMin));
    // Same number, not merely the same order of magnitude.
    expect(Number(quoted)).toBe(Math.round(realPeak));
  });
});
