/**
 * The computed numbers. Generated by `npm run compute` from demo-profile.ts —
 * see scripts/compute-demo.ts. Nothing here is typed by hand.
 */
import demo from "./data/demo.json";

export const DEMO = demo;
export type Demo = typeof demo;

/** Display strings straight from the app's formatIndex(). */
export const SCORE = {
  split: Number(demo.indexes.splitDisplay),
  splitDisplay: demo.indexes.splitDisplay,
  splitTier: demo.indexes.splitTier,
  lab: demo.indexes.labDisplay ?? "—",
  labTier: demo.indexes.labTier ?? "",
  engine: demo.indexes.engineDisplay ?? "—",
  engineTier: demo.indexes.engineTier ?? "",
} as const;

const s2c = demo.interference.strengthToCardio;
const delta = s2c.headlineDeltaPct ?? 0;
const hr = s2c.headlineHrDeltaBpm ?? 0;

export const RADAR = {
  /** e.g. "−8.8%" — typographic minus, as a designer would set it. */
  deltaLabel: `${delta < 0 ? "−" : "+"}${Math.abs(delta)}%`,
  hrLabel: `${hr > 0 ? "+" : hr < 0 ? "−" : ""}${Math.abs(hr)} bpm`,
  sentence: s2c.summary,
  sampleCount: s2c.sampleCount,
  decay: s2c.decayByDay.filter((d) => d.sampleCount > 0),
  /** The app's own micro-label above this finding (interference-radar-card.tsx). */
  question: "Does lifting slow your cardio?",
  metricLabel: "Efficiency",
} as const;

export const BOARD = demo.leaderboard;
