-- Split Index — Migration 002
-- Adds: sports reference table, strength scores, scoring reference values,
-- sleep logs, leaderboards (denormalized current index + period entries),
-- missing indexes, and RLS hardening for tables created in 001.
-- Requires Postgres 15+ (UNIQUE NULLS NOT DISTINCT). Supabase satisfies this.

-- ─── Enums ────────────────────────────────────────────────────────────────────
CREATE TYPE sport_category AS ENUM ('endurance', 'strength');

CREATE TYPE leaderboard_period AS ENUM ('weekly', 'monthly', 'all_time');

-- ─── Sports (reference table) ─────────────────────────────────────────────────
-- Lookup metadata for each sport. `slug` mirrors the sport_type enum used by
-- activity rows, so existing enum columns can join against this table.
CREATE TABLE sports (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug sport_type UNIQUE NOT NULL,
  name TEXT NOT NULL,
  category sport_category NOT NULL,
  icon TEXT,
  description TEXT,
  supports_distance BOOLEAN NOT NULL DEFAULT TRUE,
  display_order SMALLINT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

COMMENT ON TABLE sports IS
  'Reference/lookup table for supported sports. slug mirrors the sport_type enum.';

INSERT INTO sports (slug, name, category, icon, supports_distance, display_order) VALUES
  ('running',        'Running',        'endurance', '🏃', TRUE,  1),
  ('walking',        'Walking',        'endurance', '🚶', TRUE,  2),
  ('swimming',       'Swimming',       'endurance', '🏊', TRUE,  3),
  ('rowing',         'Rowing',         'endurance', '🚣', TRUE,  4),
  ('bike_erg',       'BikeErg',        'endurance', '🚴', TRUE,  5),
  ('indoor_cycling', 'Indoor Cycling', 'endurance', '🚴', TRUE,  6),
  ('ski_erg',        'SkiErg',         'endurance', '⛷️', TRUE,  7),
  ('gym',            'Gym',            'strength',  '🏋️', FALSE, 8);

-- ─── Strength Scores ──────────────────────────────────────────────────────────
-- Per-exercise strength scoring for a session, distinct from the aggregate
-- workout_scores row. One row per scored exercise within a gym activity.
CREATE TABLE strength_scores (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  activity_id UUID NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
  gym_exercise_id UUID REFERENCES gym_exercises(id) ON DELETE CASCADE,
  exercise_name TEXT NOT NULL,
  muscle_group TEXT,
  estimated_1rm_kg NUMERIC(6,2) NOT NULL CHECK (estimated_1rm_kg > 0),
  bodyweight_kg NUMERIC(5,1) CHECK (bodyweight_kg > 0),
  -- estimated_1rm_kg / bodyweight_kg at time of scoring
  relative_strength NUMERIC(5,2) CHECK (relative_strength > 0),
  volume_load_kg NUMERIC(10,2) CHECK (volume_load_kg >= 0),
  strength_index INTEGER NOT NULL CHECK (strength_index >= 0 AND strength_index <= 999),
  score_breakdown JSONB NOT NULL DEFAULT '{}',
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_strength_scores_user_time ON strength_scores(user_id, recorded_at DESC);
CREATE INDEX idx_strength_scores_user_exercise ON strength_scores(user_id, exercise_name, recorded_at DESC);
CREATE INDEX idx_strength_scores_activity ON strength_scores(activity_id);

-- ─── Reference Values (scoring standards) ─────────────────────────────────────
-- Benchmark standards used by the scoring engine to normalize raw performance
-- into a 0–999 index: e.g. expected 5k pace, or big-3 1RM/bodyweight ratios,
-- segmented by sport, gender, experience level, and optional age bracket.
-- Rows with NULL age bounds apply to all ages. Gender rows exist for
-- male/female; app logic falls back for other/prefer_not_to_say.
CREATE TABLE reference_values (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  sport sport_type NOT NULL REFERENCES sports(slug),
  metric TEXT NOT NULL,
  gender gender_type NOT NULL,
  experience experience_level NOT NULL,
  age_min SMALLINT CHECK (age_min >= 13),
  age_max SMALLINT CHECK (age_max <= 120),
  value NUMERIC(12,4) NOT NULL CHECK (value > 0),
  unit TEXT NOT NULL,
  notes TEXT,
  CHECK (age_min IS NULL OR age_max IS NULL OR age_max > age_min),
  UNIQUE NULLS NOT DISTINCT (sport, metric, gender, experience, age_min, age_max)
);

CREATE INDEX idx_reference_values_lookup ON reference_values(sport, metric, gender, experience);

-- Running: benchmark 5k pace (seconds per km) per gender × experience.
INSERT INTO reference_values (sport, metric, gender, experience, value, unit, notes) VALUES
  ('running', 'benchmark_pace_5k', 'male',   'beginner',     390, 'seconds_per_km', '6:30/km — ~32:30 5k'),
  ('running', 'benchmark_pace_5k', 'male',   'intermediate', 330, 'seconds_per_km', '5:30/km — ~27:30 5k'),
  ('running', 'benchmark_pace_5k', 'male',   'advanced',     280, 'seconds_per_km', '4:40/km — ~23:20 5k'),
  ('running', 'benchmark_pace_5k', 'male',   'elite',        230, 'seconds_per_km', '3:50/km — ~19:10 5k'),
  ('running', 'benchmark_pace_5k', 'female', 'beginner',     420, 'seconds_per_km', '7:00/km — ~35:00 5k'),
  ('running', 'benchmark_pace_5k', 'female', 'intermediate', 360, 'seconds_per_km', '6:00/km — ~30:00 5k'),
  ('running', 'benchmark_pace_5k', 'female', 'advanced',     305, 'seconds_per_km', '5:05/km — ~25:25 5k'),
  ('running', 'benchmark_pace_5k', 'female', 'elite',        255, 'seconds_per_km', '4:15/km — ~21:15 5k');

-- Big-3 lifts: estimated 1RM as a multiple of bodyweight per gender × experience.
INSERT INTO reference_values (sport, metric, gender, experience, value, unit) VALUES
  ('gym', 'squat_1rm_ratio',       'male',   'beginner',     1.00, 'ratio_bodyweight'),
  ('gym', 'squat_1rm_ratio',       'male',   'intermediate', 1.50, 'ratio_bodyweight'),
  ('gym', 'squat_1rm_ratio',       'male',   'advanced',     2.00, 'ratio_bodyweight'),
  ('gym', 'squat_1rm_ratio',       'male',   'elite',        2.50, 'ratio_bodyweight'),
  ('gym', 'squat_1rm_ratio',       'female', 'beginner',     0.75, 'ratio_bodyweight'),
  ('gym', 'squat_1rm_ratio',       'female', 'intermediate', 1.25, 'ratio_bodyweight'),
  ('gym', 'squat_1rm_ratio',       'female', 'advanced',     1.50, 'ratio_bodyweight'),
  ('gym', 'squat_1rm_ratio',       'female', 'elite',        2.00, 'ratio_bodyweight'),
  ('gym', 'bench_press_1rm_ratio', 'male',   'beginner',     0.75, 'ratio_bodyweight'),
  ('gym', 'bench_press_1rm_ratio', 'male',   'intermediate', 1.25, 'ratio_bodyweight'),
  ('gym', 'bench_press_1rm_ratio', 'male',   'advanced',     1.50, 'ratio_bodyweight'),
  ('gym', 'bench_press_1rm_ratio', 'male',   'elite',        2.00, 'ratio_bodyweight'),
  ('gym', 'bench_press_1rm_ratio', 'female', 'beginner',     0.50, 'ratio_bodyweight'),
  ('gym', 'bench_press_1rm_ratio', 'female', 'intermediate', 0.75, 'ratio_bodyweight'),
  ('gym', 'bench_press_1rm_ratio', 'female', 'advanced',     1.00, 'ratio_bodyweight'),
  ('gym', 'bench_press_1rm_ratio', 'female', 'elite',        1.25, 'ratio_bodyweight'),
  ('gym', 'deadlift_1rm_ratio',    'male',   'beginner',     1.25, 'ratio_bodyweight'),
  ('gym', 'deadlift_1rm_ratio',    'male',   'intermediate', 1.75, 'ratio_bodyweight'),
  ('gym', 'deadlift_1rm_ratio',    'male',   'advanced',     2.25, 'ratio_bodyweight'),
  ('gym', 'deadlift_1rm_ratio',    'male',   'elite',        2.75, 'ratio_bodyweight'),
  ('gym', 'deadlift_1rm_ratio',    'female', 'beginner',     1.00, 'ratio_bodyweight'),
  ('gym', 'deadlift_1rm_ratio',    'female', 'intermediate', 1.25, 'ratio_bodyweight'),
  ('gym', 'deadlift_1rm_ratio',    'female', 'advanced',     1.75, 'ratio_bodyweight'),
  ('gym', 'deadlift_1rm_ratio',    'female', 'elite',        2.25, 'ratio_bodyweight');

-- ─── Sleep Logs ───────────────────────────────────────────────────────────────
CREATE TABLE sleep_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sleep_date DATE NOT NULL,
  bed_time TIMESTAMPTZ,
  wake_time TIMESTAMPTZ,
  sleep_hours NUMERIC(4,1) NOT NULL CHECK (sleep_hours >= 0 AND sleep_hours <= 24),
  quality SMALLINT CHECK (quality >= 1 AND quality <= 5),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (bed_time IS NULL OR wake_time IS NULL OR wake_time > bed_time),
  UNIQUE(user_id, sleep_date)
);

CREATE INDEX idx_sleep_logs_user_date ON sleep_logs(user_id, sleep_date DESC);

COMMENT ON COLUMN sleep_logs.quality IS 'Subjective sleep quality, 1 (poor) to 5 (excellent).';

-- ─── Leaderboards ─────────────────────────────────────────────────────────────
-- Denormalized current index on profiles avoids scanning split_index_history
-- for all-time leaderboard queries; kept in sync by trigger below.
ALTER TABLE profiles
  ADD COLUMN current_split_index INTEGER CHECK (current_split_index >= 0 AND current_split_index <= 999),
  ADD COLUMN current_endurance_index INTEGER CHECK (current_endurance_index >= 0 AND current_endurance_index <= 999),
  ADD COLUMN current_strength_index INTEGER CHECK (current_strength_index >= 0 AND current_strength_index <= 999),
  ADD COLUMN index_updated_at TIMESTAMPTZ;

CREATE INDEX idx_profiles_current_index
  ON profiles(current_split_index DESC)
  WHERE current_split_index IS NOT NULL;

CREATE OR REPLACE FUNCTION sync_profile_current_index()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE profiles SET
    current_split_index = NEW.split_index,
    current_endurance_index = NEW.endurance_index,
    current_strength_index = NEW.strength_index,
    index_updated_at = NEW.recorded_at
  WHERE user_id = NEW.user_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER split_index_history_sync_profile
  AFTER INSERT ON split_index_history
  FOR EACH ROW EXECUTE FUNCTION sync_profile_current_index();

-- Period leaderboards (weekly/monthly/all_time), refreshed by a scheduled job
-- (pg_cron or an edge function) using the service role — not writable by users.
-- period_start is the first day of the period (epoch date 1970-01-01 for all_time).
CREATE TABLE leaderboard_entries (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  period leaderboard_period NOT NULL,
  period_start DATE NOT NULL,
  split_index INTEGER NOT NULL CHECK (split_index >= 0 AND split_index <= 999),
  endurance_index INTEGER CHECK (endurance_index >= 0 AND endurance_index <= 999),
  strength_index INTEGER CHECK (strength_index >= 0 AND strength_index <= 999),
  rank INTEGER NOT NULL CHECK (rank > 0),
  previous_rank INTEGER CHECK (previous_rank > 0),
  computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(period, period_start, user_id)
);

CREATE INDEX idx_leaderboard_period_rank ON leaderboard_entries(period, period_start DESC, rank);
CREATE INDEX idx_leaderboard_user ON leaderboard_entries(user_id, period);

-- ─── Missing indexes for 001 tables ───────────────────────────────────────────
-- FKs are not auto-indexed in Postgres; these cover the hot access paths.
CREATE INDEX idx_body_metrics_user_time ON body_metrics(user_id, recorded_at DESC);
CREATE INDEX idx_recovery_snapshots_user_time ON recovery_snapshots(user_id, recorded_at DESC);
CREATE INDEX idx_goals_user ON goals(user_id, created_at DESC);
CREATE INDEX idx_gym_exercises_activity ON gym_exercises(activity_id);
CREATE INDEX idx_ai_feedback_user ON ai_feedback(user_id, created_at DESC);
CREATE INDEX idx_friends_friend ON friends(friend_id, status);
CREATE INDEX idx_challenge_participants_user ON challenge_participants(user_id);

-- ─── Row Level Security (new tables) ──────────────────────────────────────────
ALTER TABLE sports ENABLE ROW LEVEL SECURITY;
ALTER TABLE strength_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE reference_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE sleep_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaderboard_entries ENABLE ROW LEVEL SECURITY;

-- Read-only reference data (writes go through the service role only).
CREATE POLICY "Anyone can view sports" ON sports FOR SELECT USING (true);
CREATE POLICY "Anyone can view reference values" ON reference_values FOR SELECT USING (true);
CREATE POLICY "Anyone can view leaderboards" ON leaderboard_entries FOR SELECT USING (true);

CREATE POLICY "Users manage own strength scores" ON strength_scores FOR ALL
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage own sleep logs" ON sleep_logs FOR ALL
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ─── RLS hardening for 001 tables ─────────────────────────────────────────────
-- achievements had a public-read policy but RLS was never enabled in 001.
ALTER TABLE achievements ENABLE ROW LEVEL SECURITY;

-- Allow users to insert their own profile row (the signup trigger normally
-- creates it, but this makes client-side upserts possible if it's missing).
CREATE POLICY "Users can insert own profile" ON profiles FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY "Users can update own profile" ON profiles;
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Authenticated users can create challenges they own.
CREATE POLICY "Users can create challenges" ON challenges FOR INSERT
  WITH CHECK (auth.uid() = created_by);

-- Replace the single FOR ALL friends policy: it allowed inserting rows with
-- user_id set to someone else (forging a request *from* another user).
DROP POLICY "Users manage own friendships" ON friends;

CREATE POLICY "Users can view own friendships" ON friends FOR SELECT
  USING (auth.uid() = user_id OR auth.uid() = friend_id);

CREATE POLICY "Users can send friend requests" ON friends FOR INSERT
  WITH CHECK (auth.uid() = user_id AND status = 'pending');

CREATE POLICY "Recipients can respond to friend requests" ON friends FOR UPDATE
  USING (auth.uid() = friend_id) WITH CHECK (auth.uid() = friend_id);

CREATE POLICY "Either party can remove friendship" ON friends FOR DELETE
  USING (auth.uid() = user_id OR auth.uid() = friend_id);
