-- Run this if 002 failed partway or only profiles/goals exist.
-- Idempotent remainder of 002_scoring_reference_and_leaderboards.sql.
-- Safe when sport_category / leaderboard_period enums already exist.
-- Requires 001 to be fully applied (activities, split_index_history, friends, etc.).

-- ─── Enums ────────────────────────────────────────────────────────────────────
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sport_category') THEN
    CREATE TYPE sport_category AS ENUM ('endurance', 'strength');
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'leaderboard_period') THEN
    CREATE TYPE leaderboard_period AS ENUM ('weekly', 'monthly', 'all_time');
  END IF;
END $$;

-- ─── Sports (reference table) ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sports (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug sport_type UNIQUE NOT NULL,
  name TEXT NOT NULL,
  category sport_category NOT NULL,
  icon TEXT,
  description TEXT,
  supports_distance BOOLEAN NOT NULL DEFAULT TRUE,
  display_order SMALLINT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

COMMENT ON TABLE sports IS
  'Reference/lookup table for supported sports. slug mirrors the sport_type enum.';

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM sports LIMIT 1) THEN
    INSERT INTO sports (slug, name, category, icon, supports_distance, display_order) VALUES
      ('running',        'Running',        'endurance', '🏃', TRUE,  1),
      ('walking',        'Walking',        'endurance', '🚶', TRUE,  2),
      ('swimming',       'Swimming',       'endurance', '🏊', TRUE,  3),
      ('rowing',         'Rowing',         'endurance', '🚣', TRUE,  4),
      ('bike_erg',       'BikeErg',        'endurance', '🚴', TRUE,  5),
      ('indoor_cycling', 'Indoor Cycling', 'endurance', '🚴', TRUE,  6),
      ('ski_erg',        'SkiErg',         'endurance', '⛷️', TRUE,  7),
      ('gym',            'Gym',            'strength',  '🏋️', FALSE, 8);
  END IF;
END $$;

-- ─── Strength Scores ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS strength_scores (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  activity_id UUID NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
  gym_exercise_id UUID REFERENCES gym_exercises(id) ON DELETE CASCADE,
  exercise_name TEXT NOT NULL,
  muscle_group TEXT,
  estimated_1rm_kg NUMERIC(6,2) NOT NULL CHECK (estimated_1rm_kg > 0),
  bodyweight_kg NUMERIC(5,1) CHECK (bodyweight_kg > 0),
  relative_strength NUMERIC(5,2) CHECK (relative_strength > 0),
  volume_load_kg NUMERIC(10,2) CHECK (volume_load_kg >= 0),
  strength_index INTEGER NOT NULL CHECK (strength_index >= 0 AND strength_index <= 999),
  score_breakdown JSONB NOT NULL DEFAULT '{}',
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_strength_scores_user_time ON strength_scores(user_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_strength_scores_user_exercise ON strength_scores(user_id, exercise_name, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_strength_scores_activity ON strength_scores(activity_id);

-- ─── Reference Values (scoring standards) ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS reference_values (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  sport sport_type NOT NULL REFERENCES sports(slug),
  metric TEXT NOT NULL,
  gender gender_type NOT NULL,
  experience experience_level NOT NULL,
  age_min SMALLINT CHECK (age_min >= 13),
  age_max SMALLINT CHECK (age_max <= 120),
  value NUMERIC(12,4) NOT NULL CHECK (value > 0),
  unit TEXT NOT NULL,
  notes TEXT,
  CHECK (age_min IS NULL OR age_max IS NULL OR age_max > age_min),
  UNIQUE NULLS NOT DISTINCT (sport, metric, gender, experience, age_min, age_max)
);

CREATE INDEX IF NOT EXISTS idx_reference_values_lookup ON reference_values(sport, metric, gender, experience);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM reference_values LIMIT 1) THEN
    INSERT INTO reference_values (sport, metric, gender, experience, value, unit, notes) VALUES
      ('running', 'benchmark_pace_5k', 'male',   'beginner',     390, 'seconds_per_km', '6:30/km — ~32:30 5k'),
      ('running', 'benchmark_pace_5k', 'male',   'intermediate', 330, 'seconds_per_km', '5:30/km — ~27:30 5k'),
      ('running', 'benchmark_pace_5k', 'male',   'advanced',     280, 'seconds_per_km', '4:40/km — ~23:20 5k'),
      ('running', 'benchmark_pace_5k', 'male',   'elite',        230, 'seconds_per_km', '3:50/km — ~19:10 5k'),
      ('running', 'benchmark_pace_5k', 'female', 'beginner',     420, 'seconds_per_km', '7:00/km — ~35:00 5k'),
      ('running', 'benchmark_pace_5k', 'female', 'intermediate', 360, 'seconds_per_km', '6:00/km — ~30:00 5k'),
      ('running', 'benchmark_pace_5k', 'female', 'advanced',     305, 'seconds_per_km', '5:05/km — ~25:25 5k'),
      ('running', 'benchmark_pace_5k', 'female', 'elite',        255, 'seconds_per_km', '4:15/km — ~21:15 5k');

    INSERT INTO reference_values (sport, metric, gender, experience, value, unit) VALUES
      ('gym', 'squat_1rm_ratio',       'male',   'beginner',     1.00, 'ratio_bodyweight'),
      ('gym', 'squat_1rm_ratio',       'male',   'intermediate', 1.50, 'ratio_bodyweight'),
      ('gym', 'squat_1rm_ratio',       'male',   'advanced',     2.00, 'ratio_bodyweight'),
      ('gym', 'squat_1rm_ratio',       'male',   'elite',        2.50, 'ratio_bodyweight'),
      ('gym', 'squat_1rm_ratio',       'female', 'beginner',     0.75, 'ratio_bodyweight'),
      ('gym', 'squat_1rm_ratio',       'female', 'intermediate', 1.25, 'ratio_bodyweight'),
      ('gym', 'squat_1rm_ratio',       'female', 'advanced',     1.50, 'ratio_bodyweight'),
      ('gym', 'squat_1rm_ratio',       'female', 'elite',        2.00, 'ratio_bodyweight'),
      ('gym', 'bench_press_1rm_ratio', 'male',   'beginner',     0.75, 'ratio_bodyweight'),
      ('gym', 'bench_press_1rm_ratio', 'male',   'intermediate', 1.25, 'ratio_bodyweight'),
      ('gym', 'bench_press_1rm_ratio', 'male',   'advanced',     1.50, 'ratio_bodyweight'),
      ('gym', 'bench_press_1rm_ratio', 'male',   'elite',        2.00, 'ratio_bodyweight'),
      ('gym', 'bench_press_1rm_ratio', 'female', 'beginner',     0.50, 'ratio_bodyweight'),
      ('gym', 'bench_press_1rm_ratio', 'female', 'intermediate', 0.75, 'ratio_bodyweight'),
      ('gym', 'bench_press_1rm_ratio', 'female', 'advanced',     1.00, 'ratio_bodyweight'),
      ('gym', 'bench_press_1rm_ratio', 'female', 'elite',        1.25, 'ratio_bodyweight'),
      ('gym', 'deadlift_1rm_ratio',    'male',   'beginner',     1.25, 'ratio_bodyweight'),
      ('gym', 'deadlift_1rm_ratio',    'male',   'intermediate', 1.75, 'ratio_bodyweight'),
      ('gym', 'deadlift_1rm_ratio',    'male',   'advanced',     2.25, 'ratio_bodyweight'),
      ('gym', 'deadlift_1rm_ratio',    'male',   'elite',        2.75, 'ratio_bodyweight'),
      ('gym', 'deadlift_1rm_ratio',    'female', 'beginner',     1.00, 'ratio_bodyweight'),
      ('gym', 'deadlift_1rm_ratio',    'female', 'intermediate', 1.25, 'ratio_bodyweight'),
      ('gym', 'deadlift_1rm_ratio',    'female', 'advanced',     1.75, 'ratio_bodyweight'),
      ('gym', 'deadlift_1rm_ratio',    'female', 'elite',        2.25, 'ratio_bodyweight');
  END IF;
END $$;

-- ─── Sleep Logs ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sleep_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sleep_date DATE NOT NULL,
  bed_time TIMESTAMPTZ,
  wake_time TIMESTAMPTZ,
  sleep_hours NUMERIC(4,1) NOT NULL CHECK (sleep_hours >= 0 AND sleep_hours <= 24),
  quality SMALLINT CHECK (quality >= 1 AND quality <= 5),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (bed_time IS NULL OR wake_time IS NULL OR wake_time > bed_time),
  UNIQUE(user_id, sleep_date)
);

CREATE INDEX IF NOT EXISTS idx_sleep_logs_user_date ON sleep_logs(user_id, sleep_date DESC);

COMMENT ON COLUMN sleep_logs.quality IS 'Subjective sleep quality, 1 (poor) to 5 (excellent).';

-- ─── Leaderboards ─────────────────────────────────────────────────────────────
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS current_split_index INTEGER
  CHECK (current_split_index >= 0 AND current_split_index <= 999);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS current_endurance_index INTEGER
  CHECK (current_endurance_index >= 0 AND current_endurance_index <= 999);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS current_strength_index INTEGER
  CHECK (current_strength_index >= 0 AND current_strength_index <= 999);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS index_updated_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_profiles_current_index
  ON profiles(current_split_index DESC)
  WHERE current_split_index IS NOT NULL;

CREATE OR REPLACE FUNCTION sync_profile_current_index()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE profiles SET
    current_split_index = NEW.split_index,
    current_endurance_index = NEW.endurance_index,
    current_strength_index = NEW.strength_index,
    index_updated_at = NEW.recorded_at
  WHERE user_id = NEW.user_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS split_index_history_sync_profile ON split_index_history;
CREATE TRIGGER split_index_history_sync_profile
  AFTER INSERT ON split_index_history
  FOR EACH ROW EXECUTE FUNCTION sync_profile_current_index();

CREATE TABLE IF NOT EXISTS leaderboard_entries (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  period leaderboard_period NOT NULL,
  period_start DATE NOT NULL,
  split_index INTEGER NOT NULL CHECK (split_index >= 0 AND split_index <= 999),
  endurance_index INTEGER CHECK (endurance_index >= 0 AND endurance_index <= 999),
  strength_index INTEGER CHECK (strength_index >= 0 AND strength_index <= 999),
  rank INTEGER NOT NULL CHECK (rank > 0),
  previous_rank INTEGER CHECK (previous_rank > 0),
  computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(period, period_start, user_id)
);

CREATE INDEX IF NOT EXISTS idx_leaderboard_period_rank ON leaderboard_entries(period, period_start DESC, rank);
CREATE INDEX IF NOT EXISTS idx_leaderboard_user ON leaderboard_entries(user_id, period);

-- ─── Missing indexes for 001 tables ───────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_body_metrics_user_time ON body_metrics(user_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_recovery_snapshots_user_time ON recovery_snapshots(user_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_goals_user ON goals(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gym_exercises_activity ON gym_exercises(activity_id);
CREATE INDEX IF NOT EXISTS idx_ai_feedback_user ON ai_feedback(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_friends_friend ON friends(friend_id, status);
CREATE INDEX IF NOT EXISTS idx_challenge_participants_user ON challenge_participants(user_id);

-- ─── Row Level Security (new tables) ──────────────────────────────────────────
ALTER TABLE sports ENABLE ROW LEVEL SECURITY;
ALTER TABLE strength_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE reference_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE sleep_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaderboard_entries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view sports" ON sports;
CREATE POLICY "Anyone can view sports" ON sports FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can view reference values" ON reference_values;
CREATE POLICY "Anyone can view reference values" ON reference_values FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can view leaderboards" ON leaderboard_entries;
CREATE POLICY "Anyone can view leaderboards" ON leaderboard_entries FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users manage own strength scores" ON strength_scores;
CREATE POLICY "Users manage own strength scores" ON strength_scores FOR ALL
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users manage own sleep logs" ON sleep_logs;
CREATE POLICY "Users manage own sleep logs" ON sleep_logs FOR ALL
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ─── RLS hardening for 001 tables ─────────────────────────────────────────────
ALTER TABLE achievements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can insert own profile" ON profiles;
CREATE POLICY "Users can insert own profile" ON profiles FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create challenges" ON challenges;
CREATE POLICY "Users can create challenges" ON challenges FOR INSERT
  WITH CHECK (auth.uid() = created_by);

DROP POLICY IF EXISTS "Users manage own friendships" ON friends;

DROP POLICY IF EXISTS "Users can view own friendships" ON friends;
CREATE POLICY "Users can view own friendships" ON friends FOR SELECT
  USING (auth.uid() = user_id OR auth.uid() = friend_id);

DROP POLICY IF EXISTS "Users can send friend requests" ON friends;
CREATE POLICY "Users can send friend requests" ON friends FOR INSERT
  WITH CHECK (auth.uid() = user_id AND status = 'pending');

DROP POLICY IF EXISTS "Recipients can respond to friend requests" ON friends;
CREATE POLICY "Recipients can respond to friend requests" ON friends FOR UPDATE
  USING (auth.uid() = friend_id) WITH CHECK (auth.uid() = friend_id);

DROP POLICY IF EXISTS "Either party can remove friendship" ON friends;
CREATE POLICY "Either party can remove friendship" ON friends FOR DELETE
  USING (auth.uid() = user_id OR auth.uid() = friend_id);
