-- 003: deliberately a no-op.
--
-- This file used to create `integration_connections`, `import_jobs` and three
-- enum types for a Strava/Garmin OAuth sync that was never built. It NEVER
-- RAN against production: docs/pre-launch/migration-reconciliation.md §4
-- found both tables absent on 21 Sep 2026 and recorded 003 in the migration
-- ledger as applied anyway, because its bare `CREATE TYPE` statements would
-- abort a `supabase db push` if they were ever replayed.
--
-- So the ledger says "applied", the database has none of it, and the only
-- honest content for this number is nothing. The reconciliation doc asked for
-- the file to be deleted when a real import arrived; it is kept as this stub
-- instead because migration-numbering.test.ts treats a missing number as a
-- deleted migration worth investigating, and a stub that says why is better
-- than a gap that makes someone go and find out.
--
-- The real import — Apple Health, read-only, no partner tokens — is migration
-- 089 (logging-effort plan, phase 1). Do not revive the schema that was here:
-- if Strava or Garmin OAuth is ever built it needs a fresh migration above
-- every number on every branch, with `CREATE TYPE` guarded.
--
-- Emptied 10 October 2026.

SELECT 1;
