-- `is_blocked_pair` is executable by anon, and it should never have been.
--
-- WHAT IS EXPOSED
-- ---------------
-- The function is SECURITY DEFINER, so it runs as its owner and RLS on
-- `user_blocks` does not apply to it. It answers one question — "have these two
-- accounts blocked each other" — for any pair of user ids the caller can name.
--
-- An unauthenticated caller could therefore probe the social graph: pick two
-- account ids, learn whether there is a block between them. That is a
-- relationship between two named people, disclosed to somebody who is not
-- either of them and has not signed in.
--
-- WHY 062 DID NOT CATCH IT
-- ------------------------
-- 062 ends with what looks like exactly the right pair of statements:
--
--     revoke all on function public.is_blocked_pair(uuid, uuid) from public;
--     grant execute on function public.is_blocked_pair(uuid, uuid) to authenticated;
--
-- `REVOKE ... FROM PUBLIC` removes the implicit grant Postgres gives PUBLIC and
-- nothing else. A Supabase project bootstraps with `ALTER DEFAULT PRIVILEGES IN
-- SCHEMA public GRANT ALL ON FUNCTIONS TO anon, authenticated, service_role`,
-- so the function was ALSO granted to `anon` by name the moment it was created
-- — and a direct grant to a role survives a revoke aimed at PUBLIC.
--
-- The line reads as a restriction and performs half of one. That is the same
-- mistake main's 060, 061 and 063 made, and main's 067 is the migration that
-- fixed them. 067 could not fix this one: `is_blocked_pair` does not exist on
-- main at all — main's moderation is 057_moderation_block_and_report.sql, a
-- different implementation with different functions.
--
-- Found on 15 September 2026 by src/lib/security/function-grants.test.ts, which
-- came across from main with 065–069 and failed on its first run here. That is
-- the argument for bringing a test with the migrations it guards rather than
-- only the migrations.
--
-- If you have a psql connection, this is the question rather than the grep:
--
--     select proname, proacl from pg_proc
--      where proname = 'is_blocked_pair';
--
-- `anon=X/postgres` in proacl is the grant this removes.

revoke all on function public.is_blocked_pair(uuid, uuid) from public, anon;
grant execute on function public.is_blocked_pair(uuid, uuid) to authenticated, service_role;
