import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { PERSONAS } from "./personas";
import { simulate } from "./simulator";
import { checkAthlete, summarise, type Finding } from "./assertions";

/**
 * User acceptance tests — ten simulated athletes, driven through the real
 * scoring engines for as long as eight to twelve weeks each.
 *
 * These do not replace the unit suite; they catch a different class of thing.
 * Every function under `src/lib/scoring` can pass its own tests while a swimmer
 * still sees a number that never moves, because no unit test asks "after two
 * months, did this person get anything worth paying for". These do.
 *
 * A blocking finding fails the build. A degraded one does not, because "this
 * athlete is being short-changed" is a product decision about where to spend
 * effort rather than a reason to stop a release — but every run rewrites
 * `docs/pre-launch/uat-bot-report.md`, so nothing goes unrecorded just because
 * it was not severe enough to shout.
 */

const runs = PERSONAS.map((persona) => {
  const result = simulate(persona);
  return { persona, result, findings: checkAthlete(result) };
});

const all: Finding[] = runs.flatMap((r) => r.findings);

describe("UAT — every athlete gets a working app", () => {
  it.each(runs.map((r) => [r.persona.id, r] as const))(
    "%s can train without the app breaking",
    (_id, run) => {
      const blocking = run.findings.filter((f) => f.severity === "blocking");

      // The message is the finding itself, so a CI failure is readable without
      // opening the test — it says what the athlete experienced.
      expect(
        blocking.map((f) => `[${f.check}] ${f.detail}`).join("\n"),
        `${run.persona.who}\nWants: ${run.persona.wants}`
      ).toBe("");
    }
  );
});

describe("UAT — the engines run at all", () => {
  it.each(runs.map((r) => [r.persona.id, r] as const))(
    "%s logs every session without an exception",
    (_id, run) => {
      expect(run.result.failures).toEqual([]);
    }
  );

  it.each(runs.map((r) => [r.persona.id, r] as const))(
    "%s actually completes a realistic number of sessions",
    (_id, run) => {
      // A persona whose pattern silently produces nothing would pass every
      // other check in this file by having no data to be wrong about.
      expect(run.result.sessions.length).toBeGreaterThan(0);
    }
  );
});

describe("UAT — the simulation is deterministic", () => {
  it("gives identical results on a re-run, so a failure can be reproduced", () => {
    const a = simulate(PERSONAS[1]);
    const b = simulate(PERSONAS[1]);
    expect(a.sessions.map((s) => s.splitIndex)).toEqual(b.sessions.map((s) => s.splitIndex));
    expect(a.sessions.length).toBe(b.sessions.length);
  });
});

describe("UAT — the suite covers the sports the scoring was not built around", () => {
  it("exercises every supported sport across the persona set", () => {
    const covered = new Set(runs.flatMap((r) => r.result.sessions.map((s) => s.sport)));
    // Walking and bike_erg are intentionally absent: no persona's training
    // revolves around them, and a persona invented purely to tick a box would
    // be a fixture pretending to be an athlete. Add one when a real user does.
    for (const sport of [
      "gym",
      "running",
      "swimming",
      "rowing",
      "ski_erg",
      "indoor_cycling",
      "outdoor_cycling",
    ]) {
      expect(covered, `no persona trains ${sport}`).toContain(sport);
    }
  });
});

/*
 * The report is WRITTEN, not just printed.
 *
 * Vitest's reporter hides hook output on a passing run, which is precisely the
 * run whose output matters most: a degraded finding does not fail the build, so
 * console-only reporting means the findings nobody is forced to look at are
 * exactly the ones nobody ever sees. Writing the file also makes the report
 * diffable — "swimming dropped 40 points this week" shows up in review.
 */
afterAll(() => {
  const degraded = all.filter((f) => f.severity === "degraded");
  const blocking = all.filter((f) => f.severity === "blocking");
  const notes = all.filter((f) => f.severity === "note");

  const md = [
    "# UAT — athlete report",
    "",
    "Generated by `npx vitest run tests/uat`. Do not edit — regenerate it.",
    "",
    "Ten simulated athletes driven through the real scoring engines. Each one is",
    "a training behaviour rather than a fixture, and the checks ask whether that",
    "person got something worth paying for, not whether a function returned the",
    "number it returned last time.",
    "",
    `**${blocking.length} blocking · ${degraded.length} degraded · ${notes.length} notes** across ${runs.length} athletes.`,
    "",
    "## Athletes",
    "",
    "```",
    ...runs.map((r) => summarise(r.result, r.findings)),
    "```",
    "",
  ];

  const section = (title: string, items: Finding[], preamble: string) => {
    if (!items.length) return;
    md.push(`## ${title}`, "", preamble, "");
    for (const f of items) {
      md.push(`### ${f.persona} — ${f.check}`, "", f.detail, "");
    }
  };

  section(
    "Blocking",
    blocking,
    "The app is broken or lying for these athletes. These fail the build."
  );
  section(
    "Short-changed",
    degraded,
    "Works, but this athlete is getting less than they paid for. Does not fail the build — where to spend effort is a product decision."
  );
  section(
    "Notes",
    notes,
    "Behaviour that is arithmetically correct and still worth a human look."
  );

  md.push(
    "## Personas, and why each is here",
    "",
    ...runs.flatMap((r) => [
      `**${r.persona.id}** — ${r.persona.who}`,
      "",
      `*Wants:* ${r.persona.wants}`,
      "",
      `*Covers:* ${r.persona.covers}`,
      "",
    ])
  );

  writeFileSync(
    resolve(__dirname, "../../docs/pre-launch/uat-bot-report.md"),
    md.join("\n") + "\n"
  );

  if (blocking.length || degraded.length) {
    // eslint-disable-next-line no-console -- surfaced in CI where it is read
    console.log(
      `\nUAT: ${blocking.length} blocking, ${degraded.length} degraded — see docs/pre-launch/uat-bot-report.md\n`
    );
  }
});
